spring.application.name=gestionLocationVehicules

server.port=8085

# Base de données H2 (mémoire)
spring.datasource.url=jdbc:h2:mem:vehicledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2 (pour tester)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA - Afficher les requêtes SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (32 caractères minimum)
jwt.secret=vehiclerentalsecretkey2024springbootjwt
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.yourname=DEBUG